### ISSUE TITLE
Question about PolicyGradientModel.reward_estimation

### ISSUE THREAD

**Issue by jie85** [tensorforce/tensorforce#136]
No matter whether baseline is used,  ` PolicyGradientModel.reward_estimation ` computes cumulative rewards in one batch by using ` util.cumulative_discount ` with ` cumulative_start=0.0 ` . 
In my opinion, if the last record in the batch is not a terminal of some episode, the cumulative rewards of that episode seems wrong:
If the last record is  a terminal, the reward_estimation works fine. Actually, in this case, the cumulative rewards is the MC samples of G or Q(s,a).
If the last record is not a terminal, I think the last cumulative reward should be:  r + discount * v(s'), depends on the specific RL algorithm. Thus, the parameter ` cumulative_start ` should be set as some value function's result.  As consequence,  all the other cumulative rewards in the last episode should be corrected.
It seems the author has considered the issue in design time, because of the appearance of the parameter ` cumulative_start ` of ` util.cumulative_discount `. My question is why the parameter is not used ?

**Comment by AlexKuhnle** [comment]
That's a good point. We should fix that soon, at least to the degree possible, which I think would mean that we can use the baseline as an estimate for the last state in a batch if non-terminal, but I don't see a good way to do this if there is no baseline set. What do you think?

**Comment by bigtreeliujie** [comment]
Thank you for your quick reply, and Tensorforce is wonderful project. It’s very interesting for me to analysis current VPGModel.

## Background
I think one of the VPG variants below works correctly:
1. Monte Carlo method: make sure update the policy model at the terminal of one episode and compute the cumulative discount reward without using estimate by a value function, which makes the PG ` target = G * log(Pi) `. If the length of episode is larger than the batch size, after getting the cumulative discount reward, we could divide the samples in one episode into some batches to train with. In some environment, the episode has max timestep (such as Cart-Pole, Go), that condition is easy to satisfy.
2. If there is no terminal in the environment, which means it's a non-periodic MDP, we could use a fixed step (n) discounted reward with proper discount parameter, which makes the PG ` target = n-step-cumulative-discounted-reward * log(Pi) `. If n > 1, we need maintain a sliding window in the batch cache, and update model use every `len(batch_cache) - n + 1` samples. Specially, even in a periodic MDP, we could make n = 1, which makes the PG `target = r *log(Pi)`, however making n = 1 leads to a big variance.
3. We have a state-action value function `Q(s, a)`, which makes the PG `target = Q(s,a)*log(Pi)`. In this case, we could train the Q(s,a) by samples in batch using Q-learning. TD(n) may be a good choice to learn Q(s,a). If n=0, it is just like DQN. In this algorithm, we always collect n step samples, computed discount reward in the n steps, train Q(s,a) with `n-step-cumulative-rewards + max(Q(s’(n), a))`, and train policy with `n-step- cumulative-rewards + max(Q(s’(n), a))` or Q(s,a) directly.
4. We have a state value function `V(s)`, and we could get the state-action value function `Q(s,a) = n-step- cumulative-rewards + V(s’(n))`, which makes the PG `target = (n-step- cumulative-rewards + V(s’(n))) * log(Pi) `. As there is no action parameter in V(s), it’s much easier to train this than that in 3.
5. We have a state value function `V(s)`, and we could get the Advantage function `A(s,a)= Q(s,a) – V(s) = (n-step- cumulative-rewards + V(s’(n))) – V(s)`, which makes PG `target = A(s, a) * log(Pi)`. By the way, it is also called advantage actor critic. 

All the variant 1-4 could also be added some baseline, and the baseline could be function rather than state value function. Variant 5 could be seen like variant 4 with the state value function `V(s)` as baseline.

## Analysis of current VPGModel
In current version, if we do not fix the last non-terminal issue, then VPGModel is very similar with variant 1 or variant 2:
- If the batch size is larger than the episode lengths most of the time, it’s more like variant 1. And the last non-terminal state could be treated as a system error, which leads to a little variance.
- If the batch size is smaller than the episode lengths most of the time, especially the episode is relative very long, the environment could be approximated as a non-periodic MDP, it’s more like variant 2. The last non-terminal state could be treated as a system error, which leads to a little variance.

If we use baseline as an estimate for the last non-terminal state, then VPGModel is very similar with the mixture of variant 1 and variant 5 with variable step size n: 
- If the batch size is larger than the episode lengths most of the time, it’s more like variant 1. The samples except the last non-terminal episode in the batch is trained like variant 1. And the last non-terminal episode in a batch is trained like variant 5 with a variable step size n equal to episode length in the batch.
- If the batch size is smaller than the episode lengths most of the time, it’s more like variant 5, with the step size n is equal to batch size. And the last non-terminal episode is trained with a variable step size n equal to episode length in the batch.

## My Suggestion
1.It benefits to do a quick fix by using baseline as an estimate for the last non-terminal state.
2.In VPGModel, change `self.loss_per_instance = -log_prob * self.reward` to something like ` self.loss_per_instance = -log_prob * self.pg_target`
3.We could implement variant 1-4 separately. Besides the difference of each variant’s `pg_target`, the trajectory collection pattern is different either:
  - Variant 1 needs collect a lease one episode before train. One train batch may contain one or more episode.
  - Variant 2 assume no terminals and collect fixed length batch size for training
  - Variant 3 and 4 is set up with an configure `step_size_n`, and needs collect `step_size_n` samples as a group, one training batch may contain several groups. `step_size_n` must be not larger than batch size.
4. Variant 4 with baseline is variant 5.
5. However, I think variant 1 and 4 is enough for most cases, and variant 4 with large batch size could approximate variant 1. So it is enough to implement variant 4 only, leaving the others to users.

**Comment by AlexKuhnle** [comment]
Thanks for all your comments. I think that particularly the n-step cumulative reward is something we should support, precisely because there are environments without terminal states. In fact, the main motivation for this library is to facilitate practical RL, and many practical 'environments' probably do not have terminals. We try to not get distracted by the 'idealized' conditions of simulators.

Anyway, I was just about to look into how this could be fixed (to some degree at least), but then realized that in fact there don't seem many changes necessary. Correct me if I'm wrong: If we do not have a baseline, we can't really estimate `V(s)` for the last state in the batch, hence the best way is to only use batches with completed episodes or calculate the n-step cumulative reward. If, however, we do have a baseline, we would always use the advantage `A(s) = Q(s, a) - V(s)` and hence the best we can do is to assume perfectly estimated state values for the successor episode states of the final batch state, which would justify why we start calculating the cumulative advantage from 0. Hence the implementation is probably fine **if** we use a baseline, and not quite ideal without (but there are two possible solutions, as mentioned above).

**Comment by bigtreeliujie** [comment]
In my option, "start calculating the cumulative advantage from 0" is not perfectly correct:
For the last non-terminal state s, `Q(s, a) = r + discount * v(s**'**)`, and `A(s) = Q(s, a) - V(s) = r + discount * v(s') - v(s)` . 
In the current implementation with baseline,  the last non-terminal state's `A(s) := r - v(s)`. Maybe you mistake that the last non-terminal state `Q(s, a) = r + v(s)`, and `A(s) = Q(s, a) - V(s) = r`. 

Besides, in current implementation, we do not have the next state s' for the non-terminal state, which means even with a baseline, we can not evaluation the v(s**'**). One solution maybe leave the last non-terminal state to next batch, and evaluation the second last one's advantage function value.

**Comment by AlexKuhnle** [comment]
Hmm yes, you are probably right, I might have confused some things in my last comment. I will think about it a bit more later. But you're definitely right, the last state is missing, but we could always simulate it by dropping action/reward/etc information associated with the last state, i.e. cutting the batch sequence by one but keeping the last next_state.

**Comment by AlexKuhnle** [comment]
Improved
