### ISSUE TITLE
question: does tensorforce allow you to process sequential data?

### ISSUE THREAD

**Issue by jjakimoto** [tensorforce/tensorforce#271]
Though environment itself returns state value for only current time step, you may have to combine more than one states and concatenate them as a sequential input. 

For example, in the paper of DQN, they sample 4 sequential states from a replay memory and concatenate to feed them to CNN. 

In that case, what approach would be the best on tensorforce.
Should I implement a custom agent for that?

**Comment by AlexKuhnle** [comment]
This can usually done with the [sequence preprocessor](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/preprocessing/sequence.py). Unfortunately, however, this preprocessor doesn't currently work properly due to ongoing internal architecture changes. We expect them to finish in the next 2-4 weeks. In the meantime, you can use version 3.2, where this preprocessor should still work.

**Comment by jjakimoto** [comment]
Hi @AlexKuhnle ,
Thanks,
I will keep looking into that.

**Comment by trickmeyer** [comment]
Any update on this one?  I know some LSTM and sequence things have been on the agenda for a while.

**Comment by AlexKuhnle** [comment]
On roadmap
