### ISSUE TITLE
Transfer + Fine Tuning

### ISSUE THREAD

**Issue by batu** [tensorforce/tensorforce#507]
I am planning on importing some pre-trained networks (Inception etc...) and fine tuning the top layers to learn from pixels.

Is the best way to go about it similar to the one described in [here](https://github.com/reinforceio/tensorforce/issues/488), by using Network and LayerBasedNetwork classes?

**Comment by AlexKuhnle** [comment]
Yes, I think so. I'm not sure whether loading the pretrained variables will cause difficulties since it's only for a part of the model (in that case loading them accordingly [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L682) similar to the sync [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L663) is probably the way to go), and you would need to make sure that all variables are returned for `get_variables()`.
