### ISSUE TITLE
PGModel type in the parallel runner

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#594]
It looks like PGModel 'mlp' does not exist in the parallel runner. Is there a reason for that / will using 'network' change some results?

@jviquerat

**Comment by AlexKuhnle** [comment]
Hi,
I assume you mean 'mlp' as a baseline type in the branch? Yes, this value doesn't exist anymore, since baselines are now just also using the general network specification. So `dict(type='mlp', sizes=[32, 32])` should be equivalent to `dict(type='network', network=[dict(type='dense', size=32), dict(type='dense', size=32)])`, or in fact just `[dict(type='dense', size=32), dict(type='dense', size=32)]` should also work.

**Comment by jerabaul29** [comment]
- yes.

- perfect, sounds good! :)
