### ISSUE TITLE
possible bug with the ```max_episode_timesteps``` param of the Agent

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#628]
@AlexKuhnle I have been running code in the following configuration:

- in the agent, ```max_episode_timesteps``` is set
- in the agent, ```batch_size``` is 20
- in the env, ```max_episode_timesteps``` is not set (None)
- in the env, ```terminal``` output in execute is not set (always False).

In this case:

- episodes have the right  ```max_episode_timesteps``` until episode 19
- episode 19 hangs and never ends

To solve it, I set both  ```max_episode_timesteps``` and  ```terminal``` in the env, and then the problem went away (episode 19 also returns and everything goes fine.

**Comment by AlexKuhnle** [comment]
Are you using the runner with `max_episode_timesteps` passed as argument to `run(...)`? Can you tell whether it happens after completing the 19th episode as part of `observe` (and thus likely `update`)? If you can identify this, that may be helpful... But sounds surprising, need to check.

**Comment by AlexKuhnle** [comment]
I've used this test script to try and reproduce the error, but without success. Is there anything I'm missing?

```python
from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner


class TestEnvironment(Environment):

    def __init__(self):
        self.environment = Environment.create(environment='gym', level='CartPole-v1')

    def states(self):
        return self.environment.states()

    def actions(self):
        return self.environment.actions()

    def max_episode_timesteps(self):
        return None

    def reset(self):
        return self.environment.reset()

    def execute(self, actions):
        states, terminal, reward = self.environment.execute(actions=actions)
        return states, False, reward


def main():
    # environment = Environment.create(environment='gym', level='CartPole-v1')
    environment = TestEnvironment()

    agent = Agent.create(
        agent='ppo', environment=environment, max_episode_timesteps=10,
        batch_size=10, update_frequency=10,
        critic_network='auto',
        critic_optimizer=dict(optimizer='adam', multi_step=10, learning_rate=1e-3),
        parallel_interactions=1,
    )

    runner = Runner(agent=agent, environment=environment)

    runner.run(num_episodes=300, max_episode_timesteps=10)
    runner.close()


if __name__ == '__main__':
    main()
```

**Comment by jerabaul29** [comment]
I think we were not using the max_episode_timestep in the main(), only in the runner call.

**Comment by jerabaul29** [comment]
Sorry, it was the contrary. We were using:

- None in the env class as you use
- no max_episode_timesteps at all in the runner.run call
- max_episode_timesteps set in the agent definition

Then we expected that the value used in max_episode_timesteps in agent construction would limit the max number of time steps in the run call, but it did not (I think depending on whch cases we ran it either crashed or run infinitely).

**Comment by jerabaul29** [comment]
Now using:

```
from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner


class TestEnvironment(Environment):

    def __init__(self):
        self.environment = Environment.create(environment='gym', level='CartPole-v1')

    def states(self):
        return self.environment.states()

    def actions(self):
        return self.environment.actions()

    def max_episode_timesteps(self):
        return None

    def reset(self):
        return self.environment.reset()

    def execute(self, actions):
        states, terminal, reward = self.environment.execute(actions=actions)
        return states, False, reward


def main():
    # environment = Environment.create(environment='gym', level='CartPole-v1')
    environment = TestEnvironment()

    agent = Agent.create(
        agent='ppo', environment=environment, max_episode_timesteps=10,
        batch_size=10, update_frequency=10,
        critic_network='auto',
        critic_optimizer=dict(optimizer='adam', multi_step=10, learning_rate=1e-3),
        parallel_interactions=1,
    )

    runner = Runner(agent=agent, environment=environment)

    runner.run(num_episodes=300)
    runner.close()


if __name__ == '__main__':
    main()
```

I get

```
InvalidArgumentError (see above for traceback): assertion failed: [] [Condition x <= y did not hold element-wise:x (agent.observe/agent.core_observe/agent.core_experience/cond_1/memory.enqueue/strided_slice:0) = ] [10] [y (agent.observe/agent.core_observe/agent.core_experience/cond_1/memory.enqueue/sub_2:0) = ] [9]
         [[node agent.observe/agent.core_observe/agent.core_experience/cond_1/memory.enqueue/assert_less_equal/Assert/AssertGuard/Assert (defined at /home/jrlab/.local/lib/python3.6/site-packages/tensorforce/core/memories/queue.py:85) ]]

Episodes:   0%|                                                                                                                        | 0/300 [00:02, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]
```

I suppose the argument in the agent constructor is only an upper bound for buffer allocation in your code, and you expect to get some episode limitation from another place also, right? I think this maybe a bit confusing for the user - as the user is surprised that he needs to plug in the same value in multiple locations to get things working. What do you think?

**Comment by AlexKuhnle** [comment]
Yes, the max_episode_timesteps for the agent is just to inform some internal sizes, so that e.g. the size of the memory doesn't have to be set manually in case of PPO. That would explain the problem.

I'm not a fan of extracting arguments from the agent in the runner or similar, but the entire problem of states/actions/max_timesteps stuff was supposed to be solved by the introduction of the `environment` argument to `Agent.create(...)` plus the `max_episode_timesteps()` environment function/property. So the environment specifies everything env-specific via `states()`, `actions()`, and `max_episode_timesteps()`, can be passed to `Agent.create(...)` so that `states/actions/max_episode_timesteps` don't need to be separately be set there, and the runner will execute things correctly anyway if max-episode-timestep logic is implemented in the environment.

Hmm... that leaves only one problem: An environment which is more general but is supposed to be constrained to only run `max_episode_timesteps`... Spontaneous solution suggestion: `Environment` takes an additional argument `max_episode_timesteps`, which implementations can just pass through, and then the sub-class environment implementation takes care of the actual environment logic, including `terminal=False/True`, and the base class takes care of the max_episode_timesteps aspect (if not already taken care of) by setting `terminal=2`, that is, if the env didn't terminate before it assumes it's a "fake terminal" / "simulation abort". Thoughts?

**Comment by AlexKuhnle** [comment]
The problem is that the user shouldn't be forced to have to implement an environment (or use the runner tool), since it's not always straightforward to encapsulate the "context" in a clean reset/execute-style environment. But at the same time, if it's possible, you don't want to force the user to always write their own runner-like script, with all the little bugs that may come with it. So I don't think it's possible to avoid configuration at multiple levels (ultimately due to "surface simplification tools" like runner/env), but what could help is to add a "discouraged unless necessary" kind of note in the docs for these arguments. Plus, the runner `max_episode_timesteps` could be removed with above solution, since it's always better to set the max_steps in the env than only for the runner.

**Comment by jerabaul29** [comment]
I wonder if adding some 'automatic warnings' may help.

For example, calling a

```
from tensorforce import automatic_warning

automatic_warning.enable_warnings()
```

that would provide verbose warnings such as 'be careful, you did XX which may be inconsistent with XX'.

I understand this may be low priority though.

**Comment by AlexKuhnle** [comment]
Yes, something like that would be great.

**Comment by AlexKuhnle** [comment]
Seems to work now...
