### ISSUE TITLE
Missing concrete function in the saved optimized Protobuf model

### ISSUE THREAD

**Issue by bezineb5** [tensorforce/tensorforce#662]
Hi,

I tried the new feature to export a .pb file containing only what's needed for inference. It works well, thanks!
However, it's missing a [concrete function](https://www.tensorflow.org/guide/concrete_function?hl=en) with a model signature in order to use it easily:
```python
>>> imported = tf.saved_model.load(model_path)
>>> imported.signatures
_SignatureMap({})
```

I'm looking at a way to add it, but I'm not familiar with tensorflow 2.0.

Best regards,
Ben

**Comment by AlexKuhnle** [comment]
Tensorforce is currently still based on TF1 internally in some fundamental aspects, like using sessions, using one graph instead of `tf.function`, etc. While the signature information should be contained in the file, I assume that the TF2 saved_model functions just don't make use of it, and I'm not sure there's an easy "fix". However, I'm currently working on porting the code fully to TF2, which will then use these saved_model functions etc and hence should work without problems. I can let you know when it's in a useable state (see `tf2` branch, but right now not everything works).

**Comment by bezineb5** [comment]
Thanks! I'm waiting until the tf2 branch is usable, then.

Also, is there any reason why scipy is set to 1.2.0 in the requirements? Tensorflow 2.1 requires at least version 1.4.1 so it would be better to align. I'm using 1.4.1 with tensorforce and I don't have any issue.

**Comment by AlexKuhnle** [comment]
There probably was one a long time ago, and it wasn't removed since then. But will do now, thanks for pointing it out. (In fact, I don't think it's currently used at all, at least in the main folder...)

**Comment by bezineb5** [comment]
I suggest closing this issue, as it's going to be deprecated soon. I started to look at the same on the branch tf2, I'll open an issue specific to it.
