### ISSUE TITLE
How to add exploration parameters to an agent?

### ISSUE THREAD

**Issue by etenedrac** [tensorforce/tensorforce#663]
I am exploring the code and I have seen that there are implemented several exploration strategies, like for instance OrnsteinUhlenbeck. I am wondering how can I tune the agent so as to use this strategy.  Thanks!

**Comment by AlexKuhnle** [comment]
Hi,
wherever [in the docs](https://tensorforce.readthedocs.io/en/latest/agents/ppo.html) you find an argument type specified as "parameter", in particular for the "exploration" parameter, you can specify it as a scheduled ["dynamic hyperparameter"](https://tensorforce.readthedocs.io/en/latest/basics/specification.html#static-vs-dynamic-hyperparameters), see options [here](https://tensorforce.readthedocs.io/en/latest/modules/parameters.html). So Ornstein-Uhlenbeck exploration should be possible to specify via:
```python
exploration=dict(type='ornstein_uhlenbeck')
```
(I just realised that the parameters page is missing the otherwise existing "specification key" information, like to refer to OU as `'ornstein_uhlenbeck'`. But the types are what you would expect.) Let me know if this should cause problems... Since there have been some changes around parameters recently, if it should throw an exception, please re-open.

**Comment by etenedrac** [comment]
This solved the issue. Thanks for the rapid response!
