### ISSUE TITLE
What is the purpose of num_parallel?

### ISSUE THREAD

**Issue by sccrthlt** [tensorforce/tensorforce#665]
What is the purpose of `tensorforce.execution.runner.Runner.num_parallel`?  It seems this may have had an application if/when an A3C agent was implemented.  Now it just seems it's just spawning multiple identical agents, all operating on their own environments, without performing any type of mutual gradient updates.  Is this a correct understanding?  If so, is there any plans for a MARL setup?

**Comment by AlexKuhnle** [comment]
Not quite: You're right that at some point Tensorforce was leveraging the then distributed-TF feature to enable a sophisticated distributed setup with async updates etc, but this is not working anymore and code/arg remnants will be removed (for now) in the next version. However, `num_parallel` now does not spawn multiple agents but multiple environments, and communicates via multiprocessing or sockets with them, whereas a single agent maintains multiple parallel event / act-observe streams, so a simpler multiple-worker single-agent distributed setup, not leveraging any distributed TF features. It should definitely work in the sense that if you're, for instance, using PPO with a batch-size of 20, using >1 <=20 parallel environments means the batch is filled more quickly and the agent learns faster (in terms of absolute time).

Regarding MARL: I don't think this will happen anytime soon, since I don't really know MARL, so in the shorter-term the only way would be contribution via PR. I'm happy to help with this, if you would want to look into it.
