### ISSUE TITLE
Parallel environments inconsistent behavior 

### ISSUE THREAD

**Issue by galatolofederico** [tensorforce/tensorforce#667]
Hi, first time user here. I have read the documentation but i couldn't find anything about this behavior.
I am trying to understand how to run parallel environment. When i try to run this 
```
runner = Runner(
    agent="ppo",
    environment="CartPole-v1",
    num_parallel=2
)

runner.run(num_episodes=300)
```
It works fine. But if i change `ppo` with `a2c` like this
```
runner = Runner(
    agent="a2c",
    environment="CartPole-v1",
    num_parallel=2
)

runner.run(num_episodes=300)
```
It raises
```
tensorforce.exception.TensorforceError: Invalid value for agent argument update given parallel_interactions > 1: {'unit': 'timesteps', 'batch_size': 10}.
```
I am using the latest pip version of tensorforce.
By the way is there a way to use gym vectorized environments instead of multiprocessing?

**Comment by AlexKuhnle** [comment]
Hi,

You raise an interesting problem -- the parallelization was mainly tested with "episode-based" policy gradient algos so far, and apparently too little focus on the others. The problem is related to the way Tensorforce buffers timesteps and estimates returns, which works fine in the parallelized setting if the model is working with complete episodes, but gets confusing when you move to the timestep-level. Nonetheless, this should work of course -- let me have a look at it and come back to you.

Regarding Gym vectorized environments, I wasn't aware there are optimized versions. Could you post a link and I'll have a look as well.

**Comment by galatolofederico** [comment]
[This](https://github.com/openai/gym/pull/1513) is the PR in which vectorized environments where introduced in gym  but as far as i can tell vectorized environments still uses multiprocessing underneath (as you can see [here](https://github.com/openai/gym/blob/f2c9793eb762c26bb0b5524f5f69cdd536688f2e/gym/vector/async_vector_env.py#L25)) 
I dont know tensorforce very well right now but i think that there is no reason to support them if the multiprocessing works fine.
I have worked with some RL frameworks before (always with pytorch but i know tf) so if you need some help solving this issue let me know!

**Comment by AlexKuhnle** [comment]
Thanks, I will let you know. It probably just requires modifying the way things are (auto-)configured and exceptions are thrown. I will have time to look at it latest over the weekend.

**Comment by galatolofederico** [comment]
Thanks a lot! can you please give me an minimum working example of A2C with parallel environments so that i can use that in the mean time?

**Comment by AlexKuhnle** [comment]
I just had a closer look at it, and I will probably need to think a bit more how best to make parallelization and timestep-based agents compatible. Ultimately, it will probably end up buffering parallel experience streams until the episode is complete, and only then feed it into memory (otherwise the memory will not contain consistent episodes, but mixed up timesteps). If as a quick solution you're happy with modifying the A2C file, you could change the following [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/agents/a2c.py#L251-L254) from

```python
        update = dict(unit='timesteps', batch_size=batch_size)
        if update_frequency is not None:
            update['frequency'] = update_frequency
        optimizer = dict(type='adam', learning_rate=learning_rate)
```

to

```python
        update = dict(unit='episodes', batch_size=batch_size, frequency=1)
        optimizer = dict(type='adam', learning_rate=learning_rate)
        optimizer = dict(
            type='subsampling_step', optimizer=optimizer, fraction=subsampling_fraction
        )
        optimizer = dict(type='multi_step', optimizer=optimizer, num_steps=optimization_steps)
```

What does this do? It changes the update `unit` to `'episodes'` and `update_frequency` to `1`, so after every episode. Moreover, it borrows the optimizer from PPO, sampling a batch of episodes and performing multiple updates on subsamples. Choosing `optimization_steps` and `subsampling_fraction` accordingly, you can essentially resemble the normal A2C update, which would perform one update with a small number of timesteps every few timesteps, by instead performing a bunch of small updates at once, but less frequently only after every episode.

Unfortunately I don't have a more straightforward quick solution, but maybe I manage to improve this over the weekend.

**Comment by galatolofederico** [comment]
Thanks for your insights, now i get what is going on! As a quick fix it can work but I'm not so sure that waiting for the end of the episode to perform the updates (even with the rights `optimization_steps` and `subsampling_fraction` to mimic as much as possibile `A2C`) will be the same as `A2C`.

Online updates in `A2C` are also used to have a good exploration/exploitation ratio and in order to do so updates must be performed during the current episode (so that the agent can modify is behavior and explore new regions of the state-space).
Moreover the reward boostraping is a key feature of `A2C` and it will be useless in the scenario in which all the episodes rewards are availabe.
In chapter 1.2 of [Solving the scalarization issues of Advantage-based Reinforcement Learning Algorithms](https://arxiv.org/pdf/2004.04120.pdf) there is a nice explanation of how reward boostraping is used in `A2C` ([this](https://github.com/galatolofederico/a2c-te-nog) is the pytorch implementation)

**Comment by AlexKuhnle** [comment]
Yes, I agree, the in-episode updates need fixing, as this changes the way A2C works quite substantially. I hope I can do this soon. One technical detail will, however, be difficult to change in the framework architecture: the updates, even if scheduled on a timestep-basis, will only be able to leverage data from completed episodes, in a parallelized timestep-update setup. (Reason: update experience is sampled from memory, but it is only "safe" to add a parallel experience stream to memory once an episode is completed.)

Regarding the episode rewards, this would still work via bootstrapping as specified in the `reward_estimation` argument to the `TensorforceAgent`. So the `update` value is largely independent of how reward is estimated.

**Comment by AlexKuhnle** [comment]
Hi @galatolofederico, to keep you updated: Since the changes would require moving and adapting some core parts, and since I've been already working on some fundamental changes (branch `tf2`), I decided to delay the changes to this new version to avoid merging problems. I hope this version is very soon mostly usable, and I can then focus on fixing the parallel A2C problem.

**Comment by galatolofederico** [comment]
Thanks for the update! I'll be glad to test and use the new version in my projects. For now i will continue using stable baselines (unfortunately :sweat_smile: ) but i will keep on eye on this project!

**Comment by AlexKuhnle** [comment]
Yep, I'll post here when it's working. No need to close the issue, by the way... :-)

If stable-baselines is working for you, what is the motivation to look into other frameworks, out of interest?

**Comment by galatolofederico** [comment]
I think that stable baselines is bloated, hard to extend and very hard to do research on it. I think that we as ML community are missing a good, nicely written and reliable RL framework so i am always looking for alternatives. I like the codebase of tensorforce. Moreover tensorforce is written in TF2 that is more usable that TF1. I honestly use pytorch in my daily research but i must admit that TF2 (if used without the v1 compatibility) can be as good as pytorch. I dont like stable baselines so much that for my last paper i preferred rewriting A2C from scratch instead of using it :sweat_smile:

**Comment by AlexKuhnle** [comment]
In that case you may like the next version, since it is getting rid of the last remnants of `tf.compat.v1.XXX`. Hope I get it to work soon, and would be happy to hear your feedback then, once A2C is fixed.

**Comment by AlexKuhnle** [comment]
Took longer than hoped, but FYI: on the `tf2` branch (which will sooner or later become master), this should work now.
