### ISSUE TITLE
how to make a C++ based parallel running environment 

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#670]
Hi 
I am wondering whether I can using some existing c++ codes, which can be build for parallel running executable file, as an environment. how to create interface the for Tensorforce and c++ codes?

Yours Sincerely
Wei

**Comment by AlexKuhnle** [comment]
Hi,

Do you mean that you want to write a Python wrapper for a C++ environment? Tensorforce is not supporting such a feature -- the only C++-related feature is to export the agent computation graph via TensorFlow, which then can be loaded in C++ (however, I've never done that, so can't help much here either). However, once you've written a Python wrapper for your environment, it should be straightforward to make it compatible with Tensorforce.

**Comment by waynezw0618** [comment]
Hi,
I mean my environment is a C++ based package. In my opinion, one need data exchange between Tensorforce and the environment, in my case the c++ package, rather than exporting, is that right?. I don't know whether the tensorflow graph can handle this. or Do I need pipe or UDP for data exchange?

**Comment by AlexKuhnle** [comment]
TensorFlow graphs can be imported in C++, so in theory it could work that you save the TF graph in Python after initialization, then load it in C++ and start training there. However, I have no idea how easy or difficult this will be. Since you bring up UDP: maybe another possibility is to use a "remote" environment which communicates via a socket, which is also possible in Tensorforce and which means that the remote environment could be in any language. The [socket environment](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/socket_environment.py) may give you an idea whether this can work for you.

**Comment by AlexKuhnle** [comment]
Any news here?
