### ISSUE TITLE
Recreating the NAF Agent

### ISSUE THREAD

**Issue by SomeshDaga** [tensorforce/tensorforce#674]
Hi

I am attempting to create a NAF agent (as closely as possible to the original paper), and it seems that there are some references to the DQN Agent being able to replicate its behaviour. However, I am not able to see the what configurations would be required to achieve this. I'd be glad if you could provide some pointers.

It seems that the explicit NAF Agent was removed during the major revision change from 0.4.4 -> 0.5.0. It was visible there that the computation of q-value from the advantage and state-value functions was composed as in the original paper.

**Comment by AlexKuhnle** [comment]
Hi,

Yes, it was removed because, if I remember correctly, it was difficult to make it compatible with some overall architecture changes -- the tendency is to favor an overall unified and coherent architecture over preserving specific modifications in single algorithms. And yes, some configuration of DQN was quite similar to NAF, although not the same. Let me check over the weekend and come back to you with a few more details on this.

**Comment by SomeshDaga** [comment]
Sure. I really appreciate it. Totally understand the rationale behind the architectural changes.

**Comment by AlexKuhnle** [comment]
I think it shouldn't be problematic to take parts of the old Tensorforce NAF code and implement a custom distribution class (the module which represents the "final action-mapping layer", where NAF involves the positive-definite matrix etc). Would you want to try it yourself? Otherwise I can also give it a go... However, I would probably implement it for the new version that I'm currently working on and that will soon become new master (see `tf2` branch, it's almost ready).

**Comment by SomeshDaga** [comment]
@AlexKuhnle I can try to do that. Out of curiosity, do you have an estimate for when the `tf2` branch will replace `master`? I haven't gave it a thorough look, but noticed there were changes introduced in the distribution classes. If it's going to be relatively soon, then I can hold off until it's ready

**Comment by AlexKuhnle** [comment]
The core functionality will be "usable" within the next few days, but it's mostly framework architecture that changes, so if you implement e.g. the `parametrize` function already, it won't be a problem to do the few adaptations to make it compatible later. But will certainly let you know.

**Comment by AlexKuhnle** [comment]
However, I think it may still be a while longer until it will replace master, since some functionality like saving/loading doesn't work yet and some changes I want to include are not yet there.

**Comment by AlexKuhnle** [comment]
FYI: Most algorithms should now be usable, however, as mentioned before, some features like saving/summaries will only be added over the next days.

**Comment by AlexKuhnle** [comment]
Closing since old issue and no short-term plan to re-implement the NAF agent. Please re-open or create a new issue if you're interested in this.
