### ISSUE TITLE
Tensorboard summarizer display graph of the networks

### ISSUE THREAD

**Issue by junwoony** [tensorforce/tensorforce#686]
Hi,

I'm new to tensorforce. I want to set the summarizer so that I can visualize policy and critic networks in tensorboard. I define my agent as,

```
agent = Agent.create(
    environment=tensorforce.environments.OpenAIGym()
    recorder = dict(
        directory = './recorder', frequency=1), #required for recording states and actions
    summarizer = dict(
        directory = 'tb', labels='all', frequency=1,
    )
)
```

Then, I display the summaries in tensorboard as,

```
%reload_ext tensorboard
log_dir = "./tb"
%tensorboard --logdir tb
```

It only shows SCALARS. Is there any way to visualize the entire networks with variables using GRAPH in tensorboard?

**Comment by AlexKuhnle** [comment]
Hey,

Unfortunately the graph recording doesn't seem to work currently. This happened when moving most of the internal code to TensorFlow 2.0. Two possible solutions:
- You could try one of the earlier versions when it was still working. I guess 0.5.2 may work well. You could just use it to plot the graph and nonetheless use the most recent version for training, since the graph is anyway only recorded at the beginning of training.
- Or wait for the next version, currently in branch `tf2`, which completes the move to TF2. Almost everything works already in this version including summaries, apart from the graph summary itself (something about that is a bit annoying, but I hope it can be fixed very soon).

**Comment by junwoony** [comment]
@AlexKuhnle  Thank you.
It seems like 0.5.2 brings another issue with ensorforce and openai I currently have. I will wait the next version of tensorforce and I hope it will come out very soon!

**Comment by AlexKuhnle** [comment]
No need to close it, good to keep it as a reminder... :-)

**Comment by AlexKuhnle** [comment]
Graph summaries are now working on the `tf2` branch, however, I fear they look very messy due to extensive use of `tf.function`, which means that every internal function ends up being its own small graph, see below (there are many more nodes). I don't know whether this is easy or even possible to improve... Why do you need the graph, out of interest? The Tensorforce graph will definitely always be quite complex due to all the internal operations... However, it would be nice if the function nodes would be nested instead of separated, as they are below.

![image](https://user-images.githubusercontent.com/14937649/83966541-a3902780-a8b2-11ea-8e4d-b79b0c7d650e.png)

**Comment by junwoony** [comment]
@AlexKuhnle 
Cool! Thanks. I just wanted to see the architecture of the policy and/or action networks to play around the the architecture/dimensions in the future.

**Comment by AlexKuhnle** [comment]
Hmm, I could actually check whether it's easily possible to just export the network graph, without the surrounding control-flow mess... will let you know.
