### ISSUE TITLE
Assertion "assert self.timestep_completed[parallel]" error when saving best_agent

### ISSUE THREAD

**Issue by lviala** [tensorforce/tensorforce#706]
Hi,

I am running a `ppo` agent ran by a parallel runner with `remote="multiprocessing"` mode. When the runner attempts to save the best_model to date, the following assertion error is raised:

![image](https://user-images.githubusercontent.com/10537427/84958090-93562480-b0ca-11ea-83bc-5af84647a171.png)

Is there a way to remedy this problem? Or should I just set `runner.run(save_best_agent = None)`?

Thanks in advance for the help.

**Comment by AlexKuhnle** [comment]
Hmm, you're right, the `save_best_agent` option is incompatible with parallel environments. There is no very straightforward way of fixing the underlying problem, and since some improvements in the next version address this, I would recommend either handling it "manually", or try whether the new version (branch `tf2`) works for your use case (it will still change a bit, but it's mostly usable).

**Comment by lviala** [comment]
Understood thank you, I'll take a look at that!
