### ISSUE TITLE
Modify the intermediate rewards according to the terminal reward

### ISSUE THREAD

**Issue by ZYtheNOOB** [tensorforce/tensorforce#721]
Hi, 

I'd like to modify the intermediate rewards in the memory of agent according to the terminal reward of this episode. I've tried `agent.get_variable('memory')` and the tensorforce told me the tensor is not in the graph. Is there anyway I can do this? Thank you.

**Comment by AlexKuhnle** [comment]
Hi,
I'm not sure I understand: do you mean that every timestep should be assigned the reward of the episode at the terminal state? If so, which of the agent types are you using?

**Comment by ZYtheNOOB** [comment]
Yes, exactly what you meant. And I am using PPO agent

> every timestep should be assigned the reward of the episode at the terminal state

**Comment by AlexKuhnle** [comment]
In that case, considering that the PPO agent as policy gradient algorithm computes the discounted cumulative reward as "return" per timestep (which is the actual "reward" used for the update), the easiest solution is probably to use a `discount` value of `1.0`, and give `0.0` reward at each timestep apart from the last one in an episode (so each timestep ends up with `1.0 * 0.0 + 1.0 * 0.0 + ... + 1.0 * TERMINAL`). Does that make sense?

**Comment by ZYtheNOOB** [comment]
That solves my problem, thanks a lot.

**Comment by ZYtheNOOB** [comment]
The reward of `TERMINAL` is known at the end of the episode, so its something like:

When executing:
- First timestep: `0`
- Second timestep: `0`
...
- Final timestep: `terminal_reward`

At the end, I have something like:
```
if terminal_reward > 0:
    timestep_reward = a
else:
    timestep_reward = b
```

So if I have `terminal_reward == -1`, the actual reward used for updating will be:
`0.99^0 * -1 + 0.99^1 * b + ... + 0.99^(n-1) * b`

**Comment by AlexKuhnle** [comment]
I see... I'm not sure whether this reward scheme will work well in practice, and it's only possible to define this using the "act-experience-update" (instead of the usual act-observe) agent-environment interaction. I've just added an [example script](https://github.com/tensorforce/tensorforce/blob/master/examples/act_experience_update.py) to illustrate it -- as you can see, here you only record experience at the end of an episode, so you can modify the intermediate reward and assign the entire list the final `terminal_reward`.
