### ISSUE TITLE
Act - Experience - Update, Error?

### ISSUE THREAD

**Issue by ZanyAK** [tensorforce/tensorforce#725]
Hi, 

I am currently aiming to implement the act - experience - update structure in my project. However, I keep running into an error. Therefore, I went to a basic example to see if the problem pops up there. Nonetheless, even when I use the example "act_experience_update_interface.py" it keeps popping up. I work with version 0.5.5. Error message:

mydirectory....\tensorforce\agents\tensorforce.py", line 407, in <lambda>
    function = (lambda x: x[last: index])
IndexError: too many indices for array

The problem occurs in the experience function. I tried to look into it myself but it was not evident where the error originated from. Using the debugger I found the failure occurs in line 409. 

succesfull execution:  407: function = (lambda x: x[last: index])
succesfull execution:  408: states_batch = util.fmap(function=function, xs=states, depth=1)
failed to execute:       409: internals_batch = util.fmap(function=function, xs=internals, depth=1)

Not sure if it is a bug or I am doing something wrong.

**Comment by AlexKuhnle** [comment]
Hi,

The `act_experience_update_interface.py` example is actually very new, and in general it would be best if you could try the most recent version -- that is, either the current GitHub master, or in 1-2 days the new pip version 0.6.0 (I will pin the version very soon). I can't remember off the top of my head what were relevant changes since 0.5.5, so would have to look into it more.

**Comment by ZanyAK** [comment]
Hi Alex,

Thanks, you're 100% correct. Using the git version it works without issues. Thanks!
