### ISSUE TITLE
should  ConfigSpace be listed as dependency

### ISSUE THREAD

**Issue by suliuzh** [tensorforce/tensorforce#730]
Hi
I am wondering if **ConfigSpace** should be listed in setup.py or requirements,txt?
As we can see, ConfigSpace is used in _tensorforce/tune.py_  as a must. But when I use "pip install tensorforce", it seems that ConfigSpace will not be installed automatically. So should ConfigSpace be listed as dependency?
![image](https://user-images.githubusercontent.com/27858725/93039538-56bea880-f67a-11ea-8990-a6b4ecae734f.png)

**Comment by AlexKuhnle** [comment]
Hi,
This should be installed as part of `hpbandster`, which is an optional setup flag, `pip install tensorforce[tune]` (not part of the main setup since the tune script is experimental). If you run `pip install hpbandster` (or `pip install --upgrade tensorforce[tune]`), it should work. But you're right, there should be a better warning, letting the user know about this optional setup flag. Also note that the tune script is currently experimental, so it can definitely be worth playing around with the "insides" of the script, e.g. the currently predefined hyperparameter value ranges, tuning objective, etc (which eventually should be configurable).

**Comment by AlexKuhnle** [comment]
I assume this can be closed then...
