### ISSUE TITLE
No longer support prioritized_replay?

### ISSUE THREAD

**Issue by junwoony** [tensorforce/tensorforce#731]
Hello,
I was trying to use prioritized experience replay, but in the tensorforce documentation, it looks like it only supports either random or recent memory replay types. I could find that there was a "prioritized_replay" option in older version of tensorforce. Am I just missing it in the latest version, or it no longer supports prioritized_replay?

Thank you

**Comment by AlexKuhnle** [comment]
Hi, yes, this feature was dropped when moving memory implementations to TensorFlow, since it's quite elaborate to implement a prioritized replay memory. Plus, there are some minor incompatibilities with certain configurations (mainly because it does not store experience in order, so it's impossible to retrieve coherent sequences of experiences). There is also no plan to implement this feature again (could potentially talk about a PR, but it's quite involved), however, there are variations of the normal replay memory with e.g. prioritizing recent memories during sampling which could be implemented more easily, if this is of interest.

**Comment by junwoony** [comment]
@AlexKuhnle 
Thank you for the response.
Is the one you just mentioned (prioritizing recent memories) `tensorforce.core.memories.Recent`?
I actually also tried to specify the agent as
```
Agent.create(...
    memory=dict(type='recent', capacity=10000), ...
)
```
but it caused an error saying it cannot perform < operation on type dict when it verifies (captacity > min_capacity). It looks like the "memory" in the Agent.create takes only integer (capacity), but not the type of memory.

**Comment by AlexKuhnle** [comment]
Ah, yes and no. Currently, there are two memory types and the only difference is: `replay` samples completely randomly from its capacity, `recent` samples strictly the most recent n timesteps/episodes. In particular, with a, say, batch size of 10 episodes, if the `recent` memory holds 100 episodes, 90 will never be sampled, which is why it should not be necessary to specify the capacity for this one but just use the default minimum one (unless `max_episode_timesteps` information is missing). Think about the `recent` memory as basically a batch-size buffer, not really a proper "memory".

All of the predefined agents use a predefined memory type, generally policy gradient uses `recent` (as they typically don't use memory, just batch buffer), Q-learning uses `replay`.

The type of prioritized replay, which I mentioned and which is easier to implement than the typical full "prioritized replay", would randomly sample, but not uniformly and instead with a distribution skewed towards the "end" of the memory (where the most recent experience is added). I've seen this in a few papers and that should be doable, so if you're interested in that, we could look into implementing it.

**Comment by junwoony** [comment]
@AlexKuhnle 
Thank you for the explanation! Yes it now all makes sense, and please take a look into implementing the prioritized replay method when you can!
