### ISSUE TITLE
Save and Restore model

### ISSUE THREAD

**Issue by junwoony** [tensorforce/tensorforce#734]
Hello,
I would like to save the model trained using multi-env, and restore/load it for evaluation using a single env.
However, the restored model does not run as expected (it acts like it's never been trained). I did the followings,

(1) Defined the agent, then

```
agent = Agent.create(
    agent='trpo', 
    ....
    )

agent_spec = agent.spec

runner = Runner(
agent=agent_spec,
environments=[setup_env() for _ in range(num_parallel)],
num_parallel=num_parallel,
remote='multiprocessing',
max_episode_timesteps=timesteps,
)
runner.run(num_episodes=1000)
```

(2) After the reward got improved, I saved the model(agent)
`runner.agent.save(directory = save_dir)
`
(3) Load the Agent later by,
`agent = Agent.load(directory = save_dir)
`

(4) Re-define the runner using a single env and run it.
```
runner2 = Runner(
    agent=agent,
    environment=setup_env(),
    max_episode_timesteps=timesteps,
)
runner2.run(num_episodes=100, evaluation=True)
```

When I load the agent and run the runner again, it looks like it learned nothing before, (reward is between 0-1, which is supposed to be > 10 if the agent is restored correctly.) Am I missing anything here?

**Comment by AlexKuhnle** [comment]
I don't see an obvious problem, so will need to try to replicate it. If you swap your environment with CartPole, can you reproduce the effect? That would make it easy for me to investigate. Also, if you only use one environment, instead of multiple in parallel, does the problem show up still?

Also, minor comment: instead of passing `agent.spec` to the runner at the beginning, you can just pass `agent`. Then you can save the agent via `agent.save(...)` (instead of `runner.agent.save(...)`), but you need to close the agent separately, so `runner.close(); agent.close()`.

**Comment by junwoony** [comment]
@AlexKuhnle I will try to use one environment first with your suggestion!

**Comment by AlexKuhnle** [comment]
Any updates on this?

**Comment by junwoony** [comment]
Yes. Using `agent` instead of `agent.spec` allowed me to save the agent after training. Btw if I save the agent after the runner runs the maximum number of epochs, does it save the latest updated agent?

**Comment by AlexKuhnle** [comment]
Yes, should do.
