### ISSUE TITLE
Way to reimplement the DQFD agent.

### ISSUE THREAD

**Issue by manuelknott** [tensorforce/tensorforce#752]
The DQfD agent (Deep-Q-learning from demonstration) was available in tensorforce version 0.2.0. Is there a particular reason why it was removed? Can we expect it to be added again?

And how hard would it be for me to reimplement it based on the current library version? Where would be the main issues? Thanks for your help!

**Comment by AlexKuhnle** [comment]
DQfD uses two separate replay memories, one normal DQN-like and one with expert demos, and two corresponding update components. This structure doesn't fit well with Tensorforce's generalized agent architecture which is shared between all agents. However, I think you could resemble DQfD by customizing the training loop: (a) use the normal act-observe environment interaction to fill the replay memory with interaction experience; (b) use `agent.experience()` to periodically add expert demos to the replay memory. As a result, the replay memory will be filled with both interaction experience and expert demos, and consequently the update batches will be mixed as well, which is almost like DQfD with its two separate memories and update components.

**Comment by Woellchen** [comment]
hey, i would also be very interested in seeing DQfD again.
however i see a small problem with your suggestion: it misses the supervised margin loss that is needed for DQfD to have any effect. because both simulation and expert transitions would be mixed in the same memory, one cannot distinguish between them anymore. hence it is not possible to apply the supervised loss to the expert transitions.
do you have any quick idea to solve this problem without going too deep into the library code?
thank you :)

**Comment by AlexKuhnle** [comment]
You're right, I forgot about the different margin loss... In that case, I think the easiest way would be to provide an external function `expert_margin_update(...)` or so, which performs this update given a batch of demos. I certainly think that the replay memory data management of the expert demos as in DQfD (as far as I remember) won't be done inside Tensorforce, but will be left to the user, since this component doesn't fit well with the internal architecture. Providing a sort of expert-update interface, however, makes sense.

**Comment by manuelknott** [comment]
@Woellchen did you give it a try? if you have any working implementation I would be very grateful if you would share it. I tried my best for some hours, but my knowledge of tensorforce is still too shallow

**Comment by AlexKuhnle** [comment]
Closing this since there is no plan to re-implement DQFD in the short term (unless via contribution).
