### ISSUE TITLE
Question / issue with LSTM layers

### ISSUE THREAD

**Issue by junwoony** [tensorforce/tensorforce#757]
Hi, I'm trying to play around with different layers to see how their impact on the performance. 
I defined policy networks as,

```
networks = [ 
"dense layers for each state observations --> state embeddings",
...
"concatenating state embeddings",
dict(type='lstm', size=64)
]
```
and my agent is 
```
agent = Agent.create(
agent=dict(type='trpo'),
...
network=networks
)
```

But it gives `TensorforceError: Invalid value for action_type-distribution argument embedding_shape: -1,64 not flattened and incompatible with action shape.`

Any suggestions to fix it? 
Btw, it does not generate the error if I use `internal_lstm`, but I'm not quit sure what is the right layer to use.

**Comment by AlexKuhnle** [comment]
Hi @junwoony, are you on the most recent Tensorforce version? Presumably not, since `internal_lstm` was renamed at some point... :-)  (`internal_rnn` --> `rnn`, and `rnn` --> `input_rnn`, and the same with `*lstm/gru`)

If you want to use an RNN unrolled over timesteps -- the typical "RNN" in RL -- `internal_rnn` (or `rnn` in more recent versions) is the right one. The other RNN expects a sequence of shape `(S, E)` (S: sequence, E: embeddings), and will output either a similar shape `(S, O)` or simply an output embedding `(O,)`. The latter doesn't happen over the sequence of timesteps, but over an input sequence, like e.g. a sentence is typically processed by an LSTM (and there is a new independent "sentence" at every timestep). Hope that helps.

**Comment by AlexKuhnle** [comment]
Did this help, any updates?
