### ISSUE TITLE
"deterministic" input exported in saved model

### ISSUE THREAD

**Issue by bezineb5** [tensorforce/tensorforce#776]
Hello,

Sorry to raise another issue :(
Why is the deterministic input is exported in saved-models? Shouldn't it always be deterministic in that case?

Example (as displayed in Netron after conversion to ONNX) - it seems not to be linked to anything:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1782448/112717111-d7c7e980-8ec0-11eb-8638-9d330778b836.png">

Unfortunately, I couldn't find how to remove it, I'm confused by the way tf saved-model works :(

Thanks,
Benjamin

**Comment by AlexKuhnle** [comment]
Yes and no. Tensorforce distinguishes between `independent`, meaning not part of the act-observe loop / not part of training, and `deterministic`, meaning not sampling / applying noise / dropout / etc. While it is often typical to combine both for inference/evaluation, one might also consider non-determinism a feature, in the sense that even for inference you may want to explore / act according to your certainty. That's why the inference-saved-model only sets `independent=True`, but leaves `deterministic` to the user. I have no idea whether saved-model allows to set default values for optional arguments, so the recommendation is to just always pass `deterministic=True`, unless you want to exploit non-determinism.

FYI, if you want to investigate, the saved-model code is [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/models/model.py#L805).

**Comment by bezineb5** [comment]
Ok, got it.
Thanks for the clarification and the pointer to the code!
