### ISSUE TITLE
ddqn on custom environment doesn't learn anything

### ISSUE THREAD

**Issue by berse2212** [tensorforce/tensorforce#777]
Hi,

I am currently trying to get a custom environment to work. But apparently my DDQN-Agent decides to basically not learn anything. He just chooses the same action for like 100 tries straight, then switches it up for another one on repeat...

This is my custom environment:

```
class JShowdownEnvironment(Environment):
    roomId = ''

    def __init__(self):
        super().__init__()
        print("init")
        requests.put("http://localhost:1337/init")

    def states(self):
        return dict(type="float", shape=(9,), min_value=-1, max_value=300)

    def actions(self):
        return dict(type='int', num_values=4)

    # Optional additional steps to close environment
    def close(self):
        requests.post("http://localhost:1337/close")

    def reset(self, **kwargs):
        response = requests.put("http://localhost:1337/room/reset").json()

        self.roomId = response["roomId"]
        state = np.array(response["state"])
        return state

    def execute(self, actions):
        print("Actions:" + str(actions))
        response = requests.post("http://localhost:1337/room/" + self.roomId + "?action=" + str(actions)).json()
        next_state = np.array(response["state"])
        terminal = response["terminal"]
        reward = response["reward"]
        return next_state, terminal, reward
```

Which is basically just making HTTP-Request to the real environment which is simply a Webserver.

The game is a very simple turn based fighting game where both players choose their current attack (out of 4 possible) simultaneously. The first one to die is the looser. The current opponent is set up to only choose one move. This creates an environment in which one of the attacks of the agents is simply superior to  all the other choices, so he should just use this one move. To make it a bit more difficult for the agent the moves are always in random order for each reset of the environment. This means the agent basically just has to figure which action is this best move and choose this one for the whole round. For each reset this is a different action.

States of the game are described in following array:
[126.  55.   1.  35.   0.  35.   1.  70.   0.]

the first entry is the health of the opponent ( 126 ), followed by four tuple each representing an attack. The first one being (55, 1) the second one (35, 0) an so on. The first variable in the touple is the power of the move, the second one is a simple flag. The best move to choose is always (55, 1). So in the above example the agent should choose 0 as his action.

[113.  35.   0.  70.   0.  55.   1.  35.   1.] -> action 2 is the best action.

[122.  70.   0.  35.   0.  35.   1.  55.   1.] -> action 3 is the best action.

The rest of my code is basically the Quickstart example with a few tweaks, using decaying exploration and the ddqn-Agent instead of the tensorflow-agent. I also added a few Debug-print-statements.

```
def main():

    environment = Environment.create(environment=JShowdownEnvironment, max_episode_timesteps=100)

    exploration = dict(
        type='decaying',
        decay='linear',
        unit='timesteps',
        num_steps=1000,
        initial_value=1.0,
        final_value=0.1
    )

    agent = Agent.create(
        agent='ddqn',
        environment=environment,
        batch_size=128,
        network=[
            dict(type='dense', size=200, activation='tanh'),
            dict(type='dense', size=200, activation='tanh')
        ],
        exploration=exploration,
        memory= 150000,
        predict_terminal_values=True,
        start_updating=128,
        learning_rate=0.1,
        target_sync_frequency=100,
        # state_preprocessing=None
    )

    stepsTaken = 0
    np.set_printoptions(precision=3)

    # Train for 300 episodes
    for i in range(1, 1000):

        print('Episode: ' + str(i))
        print('Steps taken: ' + str(stepsTaken))
        # Initialize episode
        states = environment.reset()
        terminal = False
        rewardSum = 0

        while not terminal:
            print()
            print("States:" + str(states))

            # Episode timestep
            actions = agent.act(states=states, deterministic=False, query=['exploration'])
            states, terminal, reward = environment.execute(actions=actions)
            stepsTaken = stepsTaken + 1
            rewardSum = rewardSum + reward
            print("Reward: " + str(reward))
            if(terminal):
                print("Finished this episode.. reward sum: " + str(rewardSum))
            agent.observe(terminal=terminal, reward=reward)

    rewardSum = 0
    for _ in range(20):
        states = environment.reset()
        internals = agent.initial_internals()
        terminal = False
        while not terminal:
            print("States:")
            print(states)

            actions, internals = agent.act(
                states=states, internals=internals,
                independent=True, deterministic=True
            )

            states, terminal, reward = environment.execute(actions=actions)
            print("Reward: " + str(reward))
            if(terminal):
                print("Finished this episode.. reward sum: " + str(rewardSum))
            rewardSum = rewardSum + reward

    print('Mean episode reward:', rewardSum / 20)

if __name__ == '__main__':
    main()
````

The output after 1000 epochs of training looks like this:

```
Episode: 996
Steps taken: 2692

States:[226.  35.   1.  55.   1.  70.   0.  35.   0.]
ExplorationRate: 0
Actions:0
Reward: -0.024000000000000007

States:[146.  35.   1.  55.   1.  70.   0.  35.   0.]
ExplorationRate: 0
Actions:2
Reward: -0.046000000000000006

States:[92. 35.  1. 55.  1. 70.  0. 35.  0.]
ExplorationRate: 0
Actions:2
Reward: -1.001
Finished this episode.. reward sum: -1.071
Episode: 997
Steps taken: 2695

States:[226.  55.   1.  35.   0.  35.   1.  70.   0.]
ExplorationRate: 0
Actions:2
Reward: -0.020000000000000004

States:[146.  55.   1.  35.   0.  35.   1.  70.   0.]
ExplorationRate: 0
Actions:2
Reward: -0.015

States:[63. 55.  1. 35.  0. 35.  1. 70.  0.]
ExplorationRate: 0
Actions:2
Reward: 1.063
Finished this episode.. reward sum: 1.028
Episode: 998
Steps taken: 2698

States:[226.  70.   0.  35.   1.  35.   0.  55.   1.]
ExplorationRate: 0
Actions:2
Reward: -0.068

States:[198.  70.   0.  35.   1.  35.   0.  55.   1.]
ExplorationRate: 0
Actions:1
Reward: -0.094

States:[198.  70.   0.  35.   1.  35.   0.  55.   1.]
ExplorationRate: 0
Actions:2
Reward: -1.062
Finished this episode.. reward sum: -1.224
Episode: 999
Steps taken: 2701

States:[226.  70.   0.  35.   1.  35.   0.  55.   1.]
ExplorationRate: 0
Actions:2
Reward: -0.07900000000000001

States:[201.  70.   0.  35.   1.  35.   0.  55.   1.]
ExplorationRate: 0
Actions:2
Reward: -0.067

States:[174.  70.   0.  35.   1.  35.   0.  55.   1.]
ExplorationRate: 0
Actions:2
Reward: -1.029
Finished this episode.. reward sum: -1.1749999999999998
```

As you can see he basically just decides to use one action over and over again. I suppose the other two actions where just random exploration actions (ignore the explorationRate, the print statement is just a fixed 0). This behavior is fine for just one game, when you figured out the best move, over the course of these 4 games the actions should have been 1, 0, 3 and 3 (on repeat in one episode). I tried a few different reward methods, the current one is basically just giving him a reward of 1 if he wins, and punishes for -1 if the agent looses and some minor rewards (punishes) for damage (taken)

Anything I am doing horrible wrong to prevent the agent from learning? I am using the version 0.6.3.

Bonus question: how can I get the current exploration rate? The method described here #709 does not seem to work anymore (TypeError: act() got an unexpected keyword argument 'query')

**Comment by AlexKuhnle** [comment]
Hi @berse2212,

This should obviously be possible to learn, below a few comments and things to try:
- Maybe most importantly, you don't want `predict_terminal_values` to be set to `True`. What it means is that it will use the Q-function to estimate the "value" of a terminal state, instead / in addition to just using the final +/-1 reward of your environment. In most cases this option doesn't need to be changed (false by default), since usually terminal states are really terminal, so no value to predict beyond the final reward.
- A `learning_rate` of `0.1` is pretty high for deep learning, more typical is something around `1e-3`.
- A `target_sync_frequency` of `100` can make sense for problems with very long training, but it basically means that only every 100th update (so in your case 100 * `batch_size=128` timesteps) the target network is updated, so I think this actually never happens in your script.
- Do I see correctly that your episodes are really short (~3 timesteps?)? In this case also the `batch_size` is maybe a bit too large, as it only happens every `128/3=~40` episodes.
- The default `state_preprocessing` value `linear_normalization` is quite important. Your state value range between -1 and 300 is not great for neural networks, usually best if values are in [0,1], [-1,1] or normally distributed around 0. `linear_normalization` takes care of this if `min/max_value` is specified in the states spec, as you have.
- I generally recommend the PPO agent, since empirically it's the easiest to get started / relatively un-sensitive to hyperparameter choice and environment behavior. But that's not to say that DDQN shouldn't work on this simple environment and it would be good to see if above comments (and maybe some manual hyperparameter tuning) helps.

Bonus question: yes, the `query` functionality in the way it was implemented wasn't compatible with TF2, so was dropped at some point. You can use TensorBoard summaries to plot parameter values (or ofc you could compute them manually based on the specification). Moreover, I've started to work on a replacement for `query`, "tracked tensors", which however right now only supports very few values. I can check whether it would be easy to add parameters over the next days.

**Comment by berse2212** [comment]
Thank you, for your fast and informative response.

I will try out this advice and report back.

The bonus question ist not very important to me right now, just wanted to use it for debug purposes. So no need to make an extra effort for me lol

**Comment by berse2212** [comment]
Hi @AlexKuhnle ,

sorry for the late response. I tried all of your suggestions but unfortunately they didn't produce good results. I then proceeded to really normalize the values (some of them did not have the -1 to 300 range but rather [-1, 1], now every value is in [-1, 1]) and it gave me way better results! Thanks for your help I did not realize the importance of normalizing values!

Also one quick note I was  and still am confused about the documentation of `target_sync_frequency`, that's why I put it on 100. Basically I read the value as N, when N being the number of time steps after which we update the target network. Simply put for my example: I do 100 steps and store them each in the replay memory. With each step I also take a sample of `batch_size` turns of the replay memory and update the policy network with them. After the 100 steps I set the weights in the target network to the current network. Thus I would have updates every 100 steps. I am now confused about the fact that the update just happens every 100 * `batch_size` steps. Can you maybe elaborate why this is the case?

**Comment by AlexKuhnle** [comment]
Yes, normalizing is very important in deep learning. Tensorforce normalizes unless the default for `state_preprocessing` is overwritten, based on the `min/max_value` in the states specification, so it's important that they define the correct range. It sounds like this wasn't the case for you? Anyway, good that it works better now.

Your understanding of `target_sync_frequency` is almost correct, it's only missing the fact that the Tensorforce implementation doesn't perform an update at every step. The update frequency is specified by `update_frequency`, which defaults to `batch_size` if not specified (so collect `batch_size` timesteps, then perform an update with a batch of size `batch_size`, etc). `target_sync_frequency`, as a consequence, doesn't specify the number of timesteps between target updates, but the number **of updates** between target updates, so the number of `update_frequency (= batch_size)` intervals. I think that should make my explanation clearer. Admittedly, using this default for `update_frequency` is not great and not typical for DQN -- I'm thinking that maybe using a float value to specify the fraction relative to `batch_size` would make sense, and `0.25` or so as default.

Let me know if there are other questions.

**Comment by AlexKuhnle** [comment]
FYI: in the latest version it's now possible to define `update_frequency` as float in `(0.0, 1.0]` which specifies the frequency relative to the batch-size. The DQN default is now `0.25`, which is more in line with typical DQN frequencies. Moreover, it's now possible to track parameter values, so if you specify `tracking='all'` and then access `agent.tracked_tensors()`, you should get the latest value of dynamic hyperparameters.

Closing this since I think all problems are addressed.
