### ISSUE TITLE
Train an Agent in an Environment then Test it on Another Environment

### ISSUE THREAD

**Issue by Zebin-Li** [tensorforce/tensorforce#846]
To whom it may concern,

I was trying to train the agent then test it in another environment. 
First, I used ` agent=Agent.create(agent="ddqn", states=environment.states(),actions=environment.actions(), network=network_spec)` to train it. 
Then, I was going to test the trained agent in the test environment using `actions = agent.act(states=environment_test.states(), independent=True, deterministic=True)`.
Please notice that I directly change the "states" from "environment.states()" to "environment_test.states()" and it gave me an error:

> raise TensorforceError.value(
tensorforce.exception.TensorforceError: Invalid value for NestedDict argument key: type reserved keyword.

I just wonder is there any way to do it other than first save the trained agent then load it in the new test environment? 
Thank you very much!

Sincerely,
Zebin Li

**Comment by Zebin-Li** [comment]
I was trying to load the trained agent will the new test environment by
`agent_test = Agent.load(directory=dir,
                   filename='agent', format ='checkpoint', environment=environment_test)`
However, the above error also occurred.
The two environments are two sets of different images, therefore, the action size and state size are different. I am not sure whether it is reasonable to load the trained agent in a new environment with different action space size and state space size.

**Comment by AlexKuhnle** [comment]
Hi @Zebin-Li,
- First, `environment.states()` returns the state space specification, not the states. You need to use `.reset()` and `.execute()` to execute an environment.
- Second, the state and action space cannot be changed, since an agent's network architecture is specific to a state/action space specification.

**Comment by Zebin-Li** [comment]
Got it, thank you!

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle,

I just wonder how about transferring the learned policy to a new environment? Can I extract the learned policy from the agent and pass it to a new agent? Thank you!

**Comment by AlexKuhnle** [comment]
Hi, if you're still talking about the type of transfer described above with changing state/action space, then this is not possible. There isn't really a difference between "agent" and "policy", at least not in that respect, since the agent's architecture is the policy architecture, which is tied to a specific space.

**Comment by Zebin-Li** [comment]
Now I understood, thank you!
