### ISSUE TITLE
States with int feature as DQN input: Dense input mismatch error

### ISSUE THREAD

**Issue by 12jr** [tensorforce/tensorforce#857]
Hi,
I have a custom Gym environment. After creating a tensorforce env from it with `tf_env = Environment.create(environment=gym_env)`, I have the following states (as expected):
```
{'x': {'type': 'int', 'shape': (), 'num_values': 5},
 'y': {'type': 'float',
  'shape': (1,),
  'min_value': 0.0,
  'max_value': 1.0},
 'z': {'type': 'float',
  'shape': (1,),
  'min_value': 0.0,
  'max_value': 1.0}}
```
When I create a simple DQN agent by
```
agent = Agent.create(
    agent = 'dqn',
    environment = tf_env,
    memory = 20000,
    batch_size = 50,
    update_frequency = .25,
    network = [
        dict(type='dense', size=hidden_sizes[0], activation='relu'),
        dict(type='dense', size=hidden_sizes[1], activation='relu')
    ],
)
```
I get the following error:
```
TensorforceError: Dense input mismatch for argument type: int != float.
```
When I change `x` to
```
{'type': 'float',
  'shape': (1,),
  'min_value': 1.0,
  'max_value': 5.0}
```
it works.

Is this expected?

**Comment by AlexKuhnle** [comment]
Yes, this is expected behavior. The reason is that categorical inputs like `0, 1, 2, 3, 4` (your `x` state component) shouldn't be interpreted as continuous values, like e.g. `0.0, 1.0, 2.0, 3.0, 4.0`. Instead, a good way to handle these is to use an embedding layer. If you use `network='auto'`, this is how they are automatically handled. Or with more configuration options: `network=dict(type='auto', size=..., depth=..., etc)` (see [here](https://tensorforce.readthedocs.io/en/latest/modules/networks.html#tensorforce.core.networks.AutoNetwork) for available parameters).
