### ISSUE TITLE
Warm start training (change the dimension of states)

### ISSUE THREAD

**Issue by chengwei-xia** [tensorforce/tensorforce#866]
Hi! Recently I want to implement a method that starts the training from more information (e.g. 10 elements in the states) and gradually reduces the dimension (e.g. reduces to 5 elements in the states for the next training iteration). Is it possible with tensorforce? How can I do that? It is like a deterministic dropout but I didn't find a way to do that.
Many thanks!

**Comment by AlexKuhnle** [comment]
Hi @chengwei-xia, changing the state space specification is not possible unfortunately. What you could do is to just introduce a "null" element, so the state always contains `n` elements, and when it should only contain `< n` elements, you fill up the remainder with this fixed "null" element. Would that work?

**Comment by chengwei-xia** [comment]
Hi @AlexKuhnle! Thanks a lot for your answer! Just to make sure, is it possible to intentionally set the corresponding weights of some specific states to zero (like disable the connection between these states and first layer of NN)?

**Comment by AlexKuhnle** [comment]
That is only possible if you implement it yourself (custom layer/network), which however I wouldn't recommend unless you're familiar with how Tensorforce layers/networks work. Note that: (a) you can't just disable a connection since a typical NN layer will always expect the same fixed-size input, and (b) setting the input to `0` is not the same as "no input" but it is just a fixed specific value which is supposed to mean "null". That's essentially the same as my recommendation of using a fixed "null" element, which is particularly straightforward if you have a state of type `int`. What does your state space look like and which bits would yo uwant to gradually remove?
