### ISSUE TITLE
is it still active?

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#890]
Hi @AlexKuhnle ,

Hope all is well :) .

A question we often discuss when starting individual RL projects is whether Tensorforce is still maintained or not, and whether we should migrate to something else. Just curious, is tensorforce "fully non maintained any longer"? (of course this is perfectly fine and understandable if you have moved on :) ). If so, could you make it clear on the repo? :)

Best,

Jean

**Comment by AlexKuhnle** [comment]
Hey Jean,

All well, thanks, hope for you too. The project is indeed "fully not maintained any longer". :-/  Unfortunately I don't have the time anymore to keep it going. Sorry if I may not have reacted to issues or similar on Github -- for most of 2022 my email notifications from Github have randomly not worked (which wasn't helpful, because I thought there seems to be no more activity on Tensorforce).

**Comment by AlexKuhnle** [comment]
I've added a warning at the top of the readme.
