### ISSUE TITLE
likelihood clipping ratio

### ISSUE THREAD

**Issue by joelvarunvasanth** [tensorforce/tensorforce#913]
Hello @AlexKuhnle ,

I have a question on the parameter 'likelihood_ratio_clipping' in the PPOAgent class(). Is this the clipping value epsilon that is used in the policy loss as described in the PPO paper by Schulman et al? ie` clip(1-epsilon, policy ratio, 1+epsilon)`?

Im confused becasue epsilon is just a clipping parameter and not a 'ratio'. Also, why is it called 'likelihood'?

**Comment by joelvarunvasanth** [comment]
Here is a link to the documentation where likelihood_ratio_clipping is mentioned - https://tensorforce.readthedocs.io/en/latest/agents/ppo.html#:~:text=likelihood_ratio_clipping%20(parameter%2C%20float%20%3E%200.0)%20%E2%80%93%20Likelihood%2Dratio%20clipping%20threshold%20(default%3A%200.25).

**Comment by AlexKuhnle** [comment]
Yes you're right. Ratio since what is clipped is a "ratio" (as you call it "policy ratio"), or more specifically, a fraction. Likelihood since it's a fraction of two likelihoods. See also [here](https://tensorforce.readthedocs.io/en/latest/modules/objectives.html#tensorforce.core.objectives.PolicyGradient).
